services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    ports:
      - "80:80"
    env_file:
      - .env
    volumes:
      - ./web:/var/www/html
    depends_on:
      - wordpress
    networks:
      - inception
    restart: unless-stopped

  wordpress:
    build: requirements/wordpress/.
    container_name: wp-php
    env_file:
      - .env
    volumes:
      - ./web:/var/www/html
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - inception
    restart: unless-stopped

  mariadb:
    build: requirements/mariadb/.
    container_name: mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - inception
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pyour_root_password"]
      timeout: 20s
      retries: 10
    command: ["--skip-grant-tables"]

networks:
  inception:
    driver: bridge

volumes:
  mariadb_data:
